### ISSUE TITLE
Secured/unsecured area

### ISSUE THREAD

**Issue by didrikpa** [difi/dc16-oidc-proxy#64]
Dersom brukeren har autorisert at vi henter informasjon for en gitt host skal denne informasjonen være i headeren selv for usikrede paths.\* 

*Kun paths som eksplisitt er konfigurert til å være totalt usikrede som bilder etc. skal ikke ha vår header.

**Comment by viktorfa** [comment]
Noen områder som bilder/static files og sånn skal ikke vite om informasjonen vi tilbyr i det hele tatt. 
Derfor må vi kunne vite om det finnes noen paths der vår spesielle header ikke skal bli med i requesten.
