### ISSUE TITLE
Redirect back to the page first requested

### ISSUE THREAD

**Issue by didrikpa** [difi/dc16-oidc-proxy#68]
Når en ikke-innlogget bruker spør om en sikret ressurs redirectes han til en idp (idporten) og kommer tilbake med en kode etter å ha blitt redirecta igjen fra idporten.

Idporten sin redirect kan kun være localhost:8080/, og en redirect til f eks www.localhost:8080/sikret-ressurs er ikke lov (man får ingen token da).

Derfor må vi på en måte vite hvilken ressurs brukeren opprinnelig spurte om hver gang en request inneholder en kode.

**Comment by viktorfa** [comment]
Man kan ha et statisk HashMap<String, String> der nøkkelen er en hash av all informasjon i en http-request som er konstant for hver klient i tillegg til host-navnet, og verdien er path-en den klienten sist spurte om.
Sånn kan man i de fleste tilfeller finne riktig path man skal redirecte til.
