### ISSUE TITLE
Handle multiple idps in one cookie

### ISSUE THREAD

**Issue by sondrew** [difi/dc16-oidc-proxy#98]
The server currently handles receiving multiple cookies with same name in the HTTP header. But when the cookie is set in the browser, it's set to path "/", the root on current host. When a user logs on host/google, the user can access can access host/google without logging in again. When the user then logs into localhost/idporten, he can access host/idporten without logging in. But when the user now performs a request on host/google, only the last cookie (host/idporten) is added to the header, causing the server to handle the request as if user is not logged in. I think this is because the cookies is set in the browser with path "/", causing only the latest one to be sent with the HTTP header. However, the browser sends with both cookies, when requesting host/someUnconfiguredPath. Setting the browser cookie with static path (e.g. "/google") however, might cause problems when accessing host's root, causing the browser to not send any cookies, as it's only configured to the path. Think we need to discuss different approaches.

**Comment by viktorfa** [comment]
Fixed in #126
